# ~/.config/starship.toml

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ"

[dart]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜"

[directory]
read_only = " ï ½"
truncation_length = 1

[docker_context]
symbol = "ïŒˆ"

[elixir]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î‰µ"
detect_extensions = ["ex", "exs"]

[elm]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜¬"

[git_branch]
disabled = false
symbol = "ï˜"

[golang]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜§"

[hg_branch]
disabled = false
symbol = "ï˜"

[java]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î‰–"

[julia]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜¤"

[memory_usage]
disabled = false
format = "$symbol [RAM: ${ram_pct}( | Swap: ${swap_pct})]($style) "
symbol = "| ï¡š"

[nim]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ïš¤"

[nix_shell]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ï‹œ"

[nodejs]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "îœ˜"

[package]
disabled = false
format = "is [$symbol $version]($style) "
symbol = "ï£–"

[perl]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î©"

[php]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜ˆ"

[python]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜†"

[ruby]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "îˆ¾"

[rust]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î¨"
detect_extensions = ["rs", "rlib"]
detect_files = ["Cargo.toml"]

[scala]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "îœ·"

[shlvl]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ï„ "

[cmake]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "ï¨¶"
style = "bold blue"

[ocaml]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î™º"
style = "bold yellow"

[c]
# symbol = "î˜"
disabled = false
format = "via [$symbol]($style) "
symbol = "î˜"
detect_extensions = ["c", "h", "cxx", "hxx", "cpp", "hpp", "c++", "h++"]

# [c++]
# symbol = "î˜"

[haskell]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î·"


[hostname]
disabled = false
format = "via [$symbol$version]($style) "
ssh_symbol = "î¬"


[lua]
disabled = false
format = "via [$symbol$version]($style) "
symbol = "î˜ "

[meson]
disabled = false
format = "[$symbol $version]($style) "
symbol = "| ï¥"

[os.symbols]
Ubuntu = "ïŒ› "
Windows = "ó°²"
Debian = "ïŒ† "

[swift]
disabled = false
format = "[$symbol$version]($style) "
symbol = "î•"

[zig]
disabled = false
format = "[$symbol]($style) "
symbol = "îš©"

[shell]
bash_indicator = "î• "
zsh_indicator = "î• "
powershell_indicator = "ï„  "

[sudo]
symbol = "ğŸ§™"
format = "[as $symbol]($style)"
allow_windows = true

[git_status]
disabled = false
